### ISSUE TITLE
It's not working 

### ISSUE THREAD

**Issue by mhipo1364** [elky/django-flat-responsive#2]
my `django` is 1.10.3, but your package doesn't work

**Comment by leportella** [comment]
for me worked to do the `collectstatic` command, otherwise it wouldn't work. I would recommend to add this on the docs

**Comment by fabiocaccamo** [comment]
It works fine and I immediately added it to [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface). 
Just run `collectstatic --noinput` or `collectstatic  --noinput --clear`

**Comment by elky** [comment]
@mhipo1364 you probably have overridden `base_site.html` in your project. I [added note](https://github.com/elky/django-flat-responsive#important-note) to README that describes how to make it work in such case. If not - please double check you have `flat_responsive` before `django.contrib.admin` in your `settings.py` and make sure your static files works properly.

@leportella yeah it's by design. On real server you have to run `collectstatic` every time you add/change any static file. But on local it must work without any additional commands.
